### PR TITLE
add setting for timezone for clock setting

### PR DESCRIPTION
**Pull request by snufflesrea**
Regarding issue #3 , it will be great if this pull can be merge with your library.
Now the clock timezone can be set programmatically.

### CODE REVIEW

**Review by arbelkilani — APPROVED** [review]
Thank you for your support!

**Comment by snufflesrea** [comment]
Hello. Can I ask question? I don't understand, although my pull request is already merged, but the method is not appear inside my app. How can I update the library?

**Comment by arbelkilani** [comment]
Hi,
A new version has been updated by jitpack, change gradle or maven version
to 1.1.
the readme.md file has been updated also.

Thanks.

**Comment by snufflesrea** [comment]
Thanks! I thought the library will be automatically updated :)

**Pull request merged**
